name: band_of_mercenaries
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  uuid: ^4.4.2
  supabase_flutter: ^2.8.4
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.12
  freezed: ^2.4.7
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  riverpod_generator: ^2.3.11
  mocktail: ^1.0.5

flutter:
  uses-material-design: true
  assets:
    - .env
